// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_i5sDBTBoq8IwrE5N2oPdr1PrhakWcA',
    appId: '1:401835657366:web:a1468a1553a77a24fa9ab7',
    messagingSenderId: '401835657366',
    projectId: 'ventapp-88784',
    authDomain: 'ventapp-88784.firebaseapp.com',
    storageBucket: 'ventapp-88784.firebasestorage.app',
    measurementId: 'G-K4ZXGFM0YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVp99-PFWiUN3Zrn0sc6cpj46bMUZ7w-k',
    appId: '1:401835657366:android:57f8ad3d2e6964d7fa9ab7',
    messagingSenderId: '401835657366',
    projectId: 'ventapp-88784',
    storageBucket: 'ventapp-88784.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9b4u8lfcbD54uLJy-m4aUabIgWe49YE',
    appId: '1:401835657366:ios:fbaeb1a3d9b3286dfa9ab7',
    messagingSenderId: '401835657366',
    projectId: 'ventapp-88784',
    storageBucket: 'ventapp-88784.firebasestorage.app',
    iosBundleId: 'com.example.controlVentapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9b4u8lfcbD54uLJy-m4aUabIgWe49YE',
    appId: '1:401835657366:ios:fbaeb1a3d9b3286dfa9ab7',
    messagingSenderId: '401835657366',
    projectId: 'ventapp-88784',
    storageBucket: 'ventapp-88784.firebasestorage.app',
    iosBundleId: 'com.example.controlVentapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5_i5sDBTBoq8IwrE5N2oPdr1PrhakWcA',
    appId: '1:401835657366:web:e6585d5ba297c20cfa9ab7',
    messagingSenderId: '401835657366',
    projectId: 'ventapp-88784',
    authDomain: 'ventapp-88784.firebaseapp.com',
    storageBucket: 'ventapp-88784.firebasestorage.app',
    measurementId: 'G-F0X9NP99F3',
  );
}
